
import { GoogleGenAI } from "@google/genai";

// Always initialize with named parameter and direct environment variable access
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const getStoreInsights = async (dataSummary: string) => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `You are an eCommerce business analyst. Analyze this store data and provide 3 short, actionable insights or recommendations: ${dataSummary}`,
      config: {
        maxOutputTokens: 500,
        temperature: 0.7,
      },
    });
    return response.text;
  } catch (error) {
    console.error("Gemini Insight Error:", error);
    return "Unable to fetch AI insights at this time.";
  }
};

export const generateProductDescription = async (productName: string, features: string) => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Write a catchy, modern marketing description (under 100 words) for a product named "${productName}" with these features: ${features}`,
    });
    return response.text;
  } catch (error) {
    console.error("Gemini Description Error:", error);
    return "Default product description generated by system.";
  }
};
